### PR TITLE
Support `@ngrx/store@7.0.0`

### PR DESCRIPTION
**Pull request by aquark**

### CODE REVIEW

**Comment by fxck** [comment]
@btroncone ? :)

**Comment by btroncone** [comment]
@ernestomancebo  I think this was just taken care of in the last PR, correct? https://github.com/btroncone/ngrx-store-logger/blob/23eaa6832605ad219ec3410c365e8547ff847cda/package.json#L22

**Comment by ernestomancebo** [comment]
@btroncone you're right. Got confused and thought the last PR was related to the `local-storage` project. I think this PR can be skip as the change is already in, also close the issue #36 and see if the #34 is related to this (haven't reviewed it fully to determine if this is the cause).

**Comment by btroncone** [comment]
Sounds good. I just issued a release as well. :)

**Pull request closed without merging**
